version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
    - "5672:5672" # Porta do AMQP (broker)
    - "15672:15672" # Porta do painel de admin do RabbitMQ
    restart: unless-stopped


  celery_worker:
    build:
      context: .
      dockerfile: docker/celery/Dockerfile
    container_name: celery_worker
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=rpc://
    volumes:
      - ./:/app
    command: ["celery", "-A", "src.tasks.celery_app.celery_app", "worker", "--loglevel=info"]
    restart: unless-stopped